image: ubuntu

before_script:
  - apt-get update
  - apt-get install -y verilator
  - apt-get install -y g++
  - apt-get install -y make

test:
  script:
    - cd spi
    - make simtest
    - make tb
