image: ubuntu

before_script:
  - apt-get update
  - apt-get install -y verilator
  - apt-get install -y clang
  - apt-get install -y make
  - apt-get install -y libfmt

test:
  script:
    - cd spi
    - make -j $(nproc) simtest
    - make -j $(nproc) tb
